# Generated by Django 4.0.3 on 2022-09-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0021_alter_rooms_price'),
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclass',
            name='booked_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.hotelbookings'),
            preserve_default=False,
        ),
    ]
