# Generated by Django 4.0.3 on 2022-09-21 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0005_rename_walletdetails_mywallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='WalletDetails',
        ),
    ]
