# Generated by Django 4.0.3 on 2022-09-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_rename_wallet_walletdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdetails',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
