# Generated by Django 4.0.1 on 2022-10-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHome', '0002_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_room',
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
