# Generated by Django 4.0.1 on 2022-10-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserHome', '0003_remove_wishlist_user_remove_wishlist_wished_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=True, upload_to='media/')),
            ],
        ),
    ]
