# Generated by Django 4.0.3 on 2022-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountSection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002D4955A88B0>', max_length=200),
        ),
    ]
