# Generated by Django 4.0.3 on 2022-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountSection', '0006_alter_userotp_uid_alter_userotp_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='userotp',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000023AEEAF88B0>', max_length=200),
        ),
    ]
