# Generated by Django 4.0.7 on 2022-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountSection', '0054_alter_userotp_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001F19F8329D0>', max_length=200),
        ),
    ]
