# Generated by Django 4.0.7 on 2022-08-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountSection', '0075_alter_userotp_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
