# Generated by Django 4.0.3 on 2022-08-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('price', models.FloatField(null=True)),
                ('img', models.ImageField(upload_to='')),
                ('Roomtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.roomtype')),
            ],
        ),
    ]
