# Generated by Django 4.0.3 on 2022-08-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_alter_rooms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='img',
            field=models.ImageField(default=True, upload_to='media'),
        ),
    ]
