# Generated by Django 4.0.3 on 2022-08-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_alter_rooms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='img',
            field=models.FileField(default=True, upload_to='media'),
        ),
    ]
