# Generated by Django 4.0.3 on 2022-08-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_alter_hotelbooking_hotel_alter_hotelbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='totalprice',
            field=models.IntegerField(null=True),
        ),
    ]
