# Generated by Django 4.0.3 on 2022-08-20 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminPanel', '0010_hotelbooking_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='AdminPanel.rooms')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
