# Generated by Django 4.0.7 on 2022-08-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0013_alter_hotelbookings_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('imageof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminPanel.rooms')),
            ],
        ),
    ]
