# Generated by Django 4.0.7 on 2022-08-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0014_multiimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimg',
            name='imageof',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AdminPanel.rooms'),
            preserve_default=False,
        ),
    ]
