# Generated by Django 4.0.7 on 2022-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0015_alter_multiimg_imageof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimg',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
