# Generated by Django 4.0.7 on 2022-08-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0017_rename_multiimg_multiimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='imageof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiimages', to='AdminPanel.rooms'),
        ),
    ]
