# Generated by Django 4.0.7 on 2022-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0018_alter_multiimage_imageof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
