# Generated by Django 4.0.3 on 2022-09-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0021_alter_rooms_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbookings',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotelbookings',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='hotelbookings',
            name='status',
        ),
    ]
