# Generated by Django 4.0.3 on 2022-09-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0022_rename_date_hotelbookings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='discount_price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='SubCategory_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Room_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Category_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.categories')),
            ],
        ),
    ]
