# Generated by Django 4.0.3 on 2022-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0023_rooms_discount_price_subcategory_offer_room_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=100)),
                ('valid_from', models.DateField(auto_now=True)),
                ('valid_to', models.DateField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
            ],
        ),
    ]
