# Generated by Django 4.0.3 on 2022-09-10 06:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminPanel', '0030_couponuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couponuser',
            new_name='Couponstatus',
        ),
    ]
