# Generated by Django 4.0.3 on 2022-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0032_rename_coupons_couponstatus_couponsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='max_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='min_amount',
            field=models.IntegerField(null=True),
        ),
    ]
