# Generated by Django 4.0.3 on 2022-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0033_coupons_max_amount_coupons_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
