# Generated by Django 4.0.3 on 2022-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0034_coupons_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
