# Generated by Django 4.0.3 on 2022-09-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code_reffered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ref_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
